name: HealthChecks v1.21.0

on:
  push:
    paths:
      - "HealthChecks/v1.21.0/**"
      - ".github/workflows/HealthChecks_v1.21.0.yaml"

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      W_DIR: HealthChecks/v1.21.0
      IMAGE_NAME: healthchecks:v1.21.0
    steps:
      - uses: actions/checkout@v2

      - name: DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: 阿里云
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALI_USERNAME }}
          password: ${{ secrets.ALI_TOKEN }}

      - name: 下载 HealthChecks 代码
        run: |
          cd ${{ env.W_DIR }} && make unzip-code

      - name: Docker Build & Push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ env.W_DIR }}/healthchecks-1.21.0
          file: ${{ env.W_DIR }}/healthchecks-1.21.0/docker/Dockerfile
          push: true
          tags: |
            qiyutech/${{ env.IMAGE_NAME }}
            ghcr.io/qiyutechdev/${{ env.IMAGE_NAME }}
            registry.cn-hangzhou.aliyuncs.com/qiyutech/${{ env.IMAGE_NAME }}
